import { useEffect, useState } from 'react'; import { Link, useNavigate, useParams } from 'react-router-dom'; import { getDocumentDownloadUrl,getDocumentScreenshots,getDocumentStatus,getDocumentSummary,getScreenshotPreviewUrl } from '../api/document'; import { retryJob } from '../api/jobs'; import { AppHeader } from '../components/AppHeader'; import { formatFileSize, formatTimestamp, friendlyContentType } from '../lib/formatting'; import type { DocumentScreenshot, DocumentStatusResponse, DocumentSummary } from '../types/api';
export function ResultPage(){const {jobId=''}=useParams();const navigate=useNavigate();const [status,setStatus]=useState<DocumentStatusResponse|null>(null);const [summary,setSummary]=useState<DocumentSummary|null>(null);const [shots,setShots]=useState<DocumentScreenshot[]>([]);const [error,setError]=useState('');const [retrying,setRetrying]=useState(false);
 useEffect(()=>{const c=new AbortController();(async()=>{try{const s=await getDocumentStatus(jobId,c.signal);setStatus(s);if(s.status==='PROCESSING'){navigate(`/jobs/${jobId}/processing`,{replace:true});return}if(s.status==='READY'){const [sum,list]=await Promise.all([getDocumentSummary(jobId,c.signal),getDocumentScreenshots(jobId,c.signal)]);setSummary(sum);setShots(list.items)}}catch{setError('Cannot connect to Notify backend.')}})();return()=>c.abort()},[jobId,navigate]);
 const retry=async()=>{setRetrying(true);try{await retryJob(jobId);navigate(`/jobs/${jobId}/processing`)}finally{setRetrying(false)}};
 if(error)return <><AppHeader/><main className="center-state"><h1>{error}</h1><button onClick={()=>location.reload()}>Retry</button></main></>;
 if(!status)return <><AppHeader/><main className="center-state">Loading your visual notes…</main></>;
 if(status.status!=='READY'){const msg=status.status==='EMPTY'?'No useful visual notes were found for this lecture.':status.status==='CORRUPT'?'The generated PDF could not be validated.':status.status==='STALE'?'This document needs to be regenerated.':status.status==='FAILED'?'Notify could not generate this document.':'Document generation has not started yet.';return <><AppHeader/><main className="center-state"><h1>{msg}</h1><div className="terminal-actions">{['STALE','CORRUPT','FAILED'].includes(status.status)&&<button onClick={retry} disabled={retrying}>{retrying?'Retrying…':'Retry Processing'}</button>}<Link className="button-link secondary" to="/">Start New Job</Link></div></main></>}
 if(!summary)return <><AppHeader/><main className="center-state">Loading your visual notes…</main></>;
 return <><AppHeader/><main className="result"><section className="result-hero"><p className="eyebrow">DOCUMENT READY</p><h1>Your visual notes are ready</h1><h2>{summary.document_title||'Lecture Notes'}</h2><div className="summary-grid"><div><strong>{summary.final_screenshot_count}</strong><span>Screenshots</span></div><div><strong>{summary.page_count}</strong><span>PDF pages</span></div><div><strong>{formatFileSize(summary.file_size_bytes)}</strong><span>File size</span></div></div><a className="download" href={getDocumentDownloadUrl(jobId)}>Download PDF</a></section><section className="gallery-section"><div className="section-heading"><div><p className="eyebrow">FINAL VISUALS</p><h2>Screenshots</h2></div><Link to="/">Start New Job</Link></div><div className="gallery">{shots.map(shot=><article className="shot-card" key={shot.candidate_id}><div className="shot-frame"><img loading="lazy" decoding="async" src={getScreenshotPreviewUrl(jobId,shot.candidate_id)} alt={`Lecture screenshot at ${shot.timestamp_display||formatTimestamp(shot.timestamp_seconds)}, ${friendlyContentType(shot.content_type)}`}/></div><div className="shot-meta"><span>{shot.timestamp_display||formatTimestamp(shot.timestamp_seconds)}</span><span>{friendlyContentType(shot.content_type)}</span></div></article>)}</div></section></main></>}
