export type UiStage='VIDEO_PREPARATION'|'VISUAL_ANALYSIS'|'CANDIDATE_SELECTION'|'TRANSCRIPTION'|'SEMANTIC_ANALYSIS'|'SCREENSHOT_SELECTION'|'DOCUMENT_PREPARATION'|'PDF_GENERATION'|'COMPLETE';
export const UI_STAGES:UiStage[]=['VIDEO_PREPARATION','VISUAL_ANALYSIS','CANDIDATE_SELECTION','TRANSCRIPTION','SEMANTIC_ANALYSIS','SCREENSHOT_SELECTION','DOCUMENT_PREPARATION','PDF_GENERATION','COMPLETE'];
export const STAGE_LABELS:Record<UiStage,string>={VIDEO_PREPARATION:'Preparing video',VISUAL_ANALYSIS:'Analyzing lecture visuals',CANDIDATE_SELECTION:'Finding useful visual states',TRANSCRIPTION:'Transcribing lecture',SEMANTIC_ANALYSIS:'Understanding lecture content',SCREENSHOT_SELECTION:'Selecting final screenshots',DOCUMENT_PREPARATION:'Preparing document',PDF_GENERATION:'Generating PDF',COMPLETE:'Notes ready'};
const map:Record<string,UiStage>={
 QUEUED:'VIDEO_PREPARATION',PREPARING:'VIDEO_PREPARATION',DOWNLOADING:'VIDEO_PREPARATION',INSPECTING_MEDIA:'VIDEO_PREPARATION',EXTRACTING_AUDIO:'VIDEO_PREPARATION',INGESTION_COMPLETE:'VIDEO_PREPARATION',
 SAMPLING_FRAMES:'VISUAL_ANALYSIS',PREPROCESSING_FRAMES:'VISUAL_ANALYSIS',DETECTING_CHANGES:'VISUAL_ANALYSIS',DETECTING_MAJOR_CHANGES:'VISUAL_ANALYSIS',DETECTING_STABILITY:'VISUAL_ANALYSIS',FRAME_ANALYSIS_COMPLETE:'VISUAL_ANALYSIS',
 GENERATING_CANDIDATES:'CANDIDATE_SELECTION',BUILDING_TEMPORAL_CONTEXT:'CANDIDATE_SELECTION',
 TRANSCRIBING:'TRANSCRIPTION',VALIDATING_AUDIO:'TRANSCRIPTION',TRANSCRIBING_AUDIO:'TRANSCRIPTION',NORMALIZING_TRANSCRIPT:'TRANSCRIPTION',ALIGNING_TRANSCRIPT:'TRANSCRIPTION',BUILDING_TRANSCRIPT_CONTEXT:'TRANSCRIPTION',
 PREPARING_SEMANTIC_INPUT:'SEMANTIC_ANALYSIS',BUILDING_VISUAL_CONTEXT:'SEMANTIC_ANALYSIS',ANALYZING_VISUAL_CANDIDATES:'SEMANTIC_ANALYSIS',SELECTING_SEMANTIC_CANDIDATES:'SEMANTIC_ANALYSIS',AI_ANALYSIS:'SEMANTIC_ANALYSIS',
 EXTRACTING_SOURCE_SCREENSHOTS:'SCREENSHOT_SELECTION',VALIDATING_SCREENSHOT_QUALITY:'SCREENSHOT_SELECTION',GENERATING_VISUAL_FINGERPRINTS:'SCREENSHOT_SELECTION',DETECTING_SCREENSHOT_DUPLICATES:'SCREENSHOT_SELECTION',SELECTING_FINAL_SCREENSHOTS:'SCREENSHOT_SELECTION',SELECTING_SCREENSHOTS:'SCREENSHOT_SELECTION',DEDUPLICATING:'SCREENSHOT_SELECTION',
 VALIDATING_DOCUMENT_CACHE:'DOCUMENT_PREPARATION',PREPARING_DOCUMENT_INPUT:'DOCUMENT_PREPARATION',PLANNING_DOCUMENT_LAYOUT:'DOCUMENT_PREPARATION',PREPARING_DOCUMENT_RENDER_PLAN:'DOCUMENT_PREPARATION',GENERATING_PDF:'PDF_GENERATION',COMPLETED:'COMPLETE'
};
export const mapBackendStageToUiStage=(stage:string):UiStage=>map[stage]||'VIDEO_PREPARATION';
